### ISSUE TITLE
No more songs

### ISSUE THREAD

**Issue by ghost** [filippotoso/mutify#3]
My spotify app is now always muted, 
how can i do, i tried to uninstall both but it doesn't work anymore

**Comment by filippotoso** [comment]
Check the Windows Mixer Volume and enable the Spotify audio in it.

**Comment by ghost** [comment]
Resolved Thank U

Il giorno mer 1 dic 2021 alle ore 10:37 Filippo Toso <
***@***.***> ha scritto:
