### ISSUE TITLE
Doesn't consistently work for Belgium

### ISSUE THREAD

**Issue by OverdueFashion** [filippotoso/mutify#4]
I'm located in Belgium and get advertisements in Dutch, not sure how I can contribute to help reduce these, but let me know if there is something I can help with.

**Comment by filippotoso** [comment]
Hi, when the advertisements start, what's the title of the Spotify application? Usually it's something like Advertisement, Spotify or Spotify Free.

**Comment by OverdueFashion** [comment]
The title is "Advertisement" when I hover over the taskbar icon, I'm using Windows 11 Pro and Spotify from the App store (Spotify for Windows (64 bit) 1.2.22.982.g794acc0a). See screen capture.
![2023-10-18 10_53_57-Clipboard](https://github.com/filippotoso/mutify/assets/17432390/94eac6ad-a685-47d1-a337-e3d085306b88)

**Comment by OverdueFashion** [comment]
here is a video version, I've got mutify in the background and the adverts still pass through

https://github.com/filippotoso/mutify/assets/17432390/f0b1a48c-970a-4948-a7dd-68704ead5f67

**Comment by filippotoso** [comment]
Please, try with the latest version I just released.

**Comment by OverdueFashion** [comment]
I just tried with the new version (MD5 hash = 860e0ea2d575ffb266eea9253faa003d) but get the same results. 

https://github.com/filippotoso/mutify/assets/17432390/4efda5bd-4f9d-4efb-ac73-9da7cc26d104

**Comment by OverdueFashion** [comment]
Not sure why but this one seems to work against Belgian ads, https://github.com/enpandi/SpotifyAdMuter

**Comment by filippotoso** [comment]
I checked the source code of the tool you suggested and it works almost in the same way. I don't know why it doesn't work for you and I have no way to replicate the problem on my end.

**Comment by OverdueFashion** [comment]
I understand, thank you for your time and consideration
